spring:
  application:
    name: wechat-application
  profiles:
    active: default
  datasource:
      url:
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 5560

logging:
  config: classpath:logback.xml

