spring:
  application:
    name: wechat-backend-service
  profiles:
    active: default
  datasource:
      url:
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 7002

logging:
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      #jar包启动参数传入eureka.host就取传入的值，不传就取localhost
      defaultZone: http://${eureka.host:localhost}:7000/eureka/
  instance:
    prefer-ip-address: true